SPHINXBUILD   = sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html
	@echo
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."
